name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt-get install libpoco-dev libpocofoundation50 libpoconet50 libpocoutil50 libgdal20 libgdal-dev cmake g++ build-essential libpq-dev discount python
    - name: configure
      run: cmake .
    - name: make
      run: make
    - name: Upload math result for build job
        uses: actions/upload-artifact@v1
        with:
          name: batyrd
          path: batyrd

  pack:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt-get install debhelper

    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        # Artifact name
        name: batyrd
    - name: make debian package
      run: make -f Makefile.devel deb
